In [1]:
import numpy as np

In [2]:
train_data_path = r'C:\Users\Zheyi\Documents\CMU\10601\hw5_new\handout\small_train_data.csv'
val_data_path = r'C:\Users\Zheyi\Documents\CMU\10601\hw5_new\handout\small_validation_data.csv'

In [3]:
def load_data(file_path):
    data = np.loadtxt(file_path, delimiter=',')
    label = data[:, 0].astype(int)
    input_x = np.hstack((np.ones((len(data),1)), data)) # add bias term
    input_x = np.delete(input_x, 1, axis = 1) # delete label
#     y = np.eye(10)[np.array(label)]
    return input_x, label

In [4]:
train_input_x, train_label = load_data(train_data_path)

In [5]:
np.shape(train_input_x) # 500 examples, 129 features for each label

(500, 129)

In [6]:
def shuffle(x, y, epoch):
    np.random.seed(epoch)
    n = len(y)
    ordering = np.random.permutation(n)
    return x[ordering], y[ordering]

In [7]:
def random_init(x, y):
    np.random.seed(np.prod((x, y)))
    weights = np.random.uniform(-0.1, 0.1, (x, y))
    weights[:, 0] = 0.0
    return weights

In [8]:
def zero_init(x, y):
    weights = np.zeros((x, y))
    return weights

In [9]:
def initial_weight(init_flag, D, M): # D: number of hidden units; M: length of each example
    if init_flag == 1:
        alpha = random_init(D, M + 1)
        beta = random_init(10, D + 1)
    elif init_flag == 2:
        alpha = zero_init(D, M + 1)
        beta = zero_init(10, D + 1)
    print(alpha)
    return alpha, beta

In [10]:
alpha, beta = initial_weight(2, 10, 129)

UnboundLocalError: local variable 'alpha' referenced before assignment

In [10]:
def sigmoid(a):
    return 1.0 / (1.0 + np.exp(-a))


def softmax(a):
    return np.exp(a) / np.sum(np.exp(a))

In [19]:
def cross_entropy(y_hat, y):
    return -np.dot(y.T, np.log(y_hat))

In [20]:
def forward(x, y, alpha, beta): # x is one example, y is the corresponding label
    a = np.dot(x, alpha);
    z_star = sigmoid(a)
    z = np.vstack((np.array([1]), z_star)) # add z_0, column vector, M+1 * 1
    
    b = np.dot(z, beta)
    y_hat = softmax(b) # row vector, 1 * 10
    
    cross_en = cross_entropy(y_hat, y)
    
    return a, b, z, y_hat, cross_en

In [ ]:
def backward()

In [12]:
z = np.array(([0, 1, 2]))
z.T

array([0, 1, 2])

In [13]:
z.reshape(-1, 1)

array([[0],
       [1],
       [2]])

python3 learnhmm.py toy_data/train.txt toy_data/index_to_word.txt toy_data/index_to_tag.txt toy_data/hmminit.txt toy_data/hmmemit.txt toy_data/hmmtrans.txt

In [16]:
a = np.array(([0, 1, 2]))
b = np.array(([3, 4, 5]))
a - b

array([-3, -3, -3])

In [23]:
z = np.array(([0, 1, 2]))
(1-z).reshape(-1, 1)

array([[ 1],
       [ 0],
       [-1]])

In [25]:
z = np.array(([0, 1, 2]))
c = np.multiply(z.reshape(-1, 1), (1 - z).reshape(-1, 1))
c

array([[ 0],
       [ 0],
       [-2]])

In [26]:
b = np.array(([3, 4, 5]))
np.multiply(c, b.reshape(-1, 1))

array([[  0],
       [  0],
       [-10]])

In [27]:
a = np.array(([0, 1, 2]))
b = np.array(([3, 4, 5]))
np.multiply(a.reshape(-1, 1), (1 - a).reshape(-1, 1), b.reshape(-1, 1))

array([[ 0],
       [ 0],
       [-2]])

In [33]:
label = [1, 2, 0, 3]
y = np.eye(10)[np.array(label)]
y

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [35]:
y[1]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
labels = [1, 2, 0, 3]
for j in range(len(labels)):
    label = labels[j]
    y = np.zeros(10)
    y[label] = 1
    
y

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])