In [1]:
import numpy as np

In [3]:
a = np.array(([1, 2, 3], [4, 5, 6]))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [6]:
for i in range(len(a)):
    for j in range(len(a[0])):
        print(a[i][j])

1
2
3
4
5
6


In [3]:
d = {0: -0.5, 1: 0.0}

In [8]:
res = np.array([list(d.values())])
type(res[0])

numpy.ndarray

In [3]:
np.random.uniform(1, 5)

2.12808203539324

In [5]:
type(np.around(np.random.uniform(1, 5)))

numpy.float64

In [7]:
type(np.random.randint(1, 5))

int

In [9]:
a = np.array([-0.5, 0])
b = np.array([[1, 2, 2], [3, 4, 5]])
np.dot(a, b)

array([-0.5, -1. , -1. ])

In [10]:
np.dot(a, b[:, 0])

-0.5

In [9]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.hstack((a, b))
c.shape

(4,)

In [15]:
d = {0: -0.5, 1: 0.0}
result = np.zeros(2)
for key, val in d.items():
    result[key] = val

In [16]:
result

array([-0.5,  0. ])